 name: Shopify Theme check
 # give the workflow just enough rights to run theme-check
 permissions:
 contents: read     # we only need to read your code
 checks: write      # allow creating the GitHub Check run

 on:
   push:
     branches:
       - main
   workflow_dispatch:
 jobs:
   theme-check:
     name: Theme Check
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v4                               # upgrade to latest checkout:contentReference[oaicite:0]{index=0}
      - name: Theme Check
        uses: shopify/theme-check-action@v2                      # Node-based, no Ruby required:contentReference[oaicite:1]{index=1}
        with:
          token: ${{ github.token }}
          # optional: if your theme lives in a subfolder, point at it:
          # theme_root: './path/to/theme'
          # optional: only annotate changes vs main
          # base: main