name: Shopify Theme Deploy

on:
  push:
    branches:
      - main        # or whatever branch you deploy from
  workflow_dispatch: # lets you run it manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v3

      # 2) Install Node
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3) Install Shopify CLI (Node edition)
      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      # 4) Push your theme
      - name: Deploy theme to Shopify
        env:
          # your repo-level secrets
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_THEME_ID: ${{ secrets.SHOPIFY_FLAG_THEME_ID }}
        run: shopify theme push -u